source 'http://rubygems.org'

gem 'rails', '4.2.5'
gem 'jquery-rails'
gem 'activerecord-session_store'

# Using sqlite by default.
gem 'sqlite3'

# AdWords API gem.
gem 'google-adwords-api'
gem 'google-api-client'

# Gem for OAuth authorization.
gem 'oauth2'
gem 'tzinfo-data'
